-- Sample Data for Avipro Travels
-- This file contains sample travel packages for testing

USE avipro_travels;

-- Insert Sample Travel Packages
INSERT INTO packages (title, slug, destination, duration, price, discount_price, description, itinerary, inclusions, exclusions, featured, status) VALUES
('Amazing Kashmir Tour', 'amazing-kashmir-tour', 'Kashmir', '5 Days / 4 Nights', 25000.00, 22000.00, 'Experience the breathtaking beauty of Kashmir with our specially curated tour package. Visit the famous Dal Lake, Gulmarg, Pahalgam, and Sonamarg. Enjoy shikara rides, gondola rides, and stay in beautiful houseboats.', 'Day 1: Arrival in Srinagar, Check-in to Houseboat\nDay 2: Visit Dal Lake, Shikara Ride, Mughal Gardens\nDay 3: Excursion to Gulmarg, Gondola Ride\nDay 4: Visit Pahalgam, Betaab Valley\nDay 5: Departure', '• Accommodation in houseboat and hotel\n• All meals (Breakfast, Lunch, Dinner)\n• Transportation\n• Guide services\n• Entry tickets', '• Airfare\n• Personal expenses\n• Tips and gratuities', 1, 'active'),

('Goa Beach Paradise', 'goa-beach-paradise', 'Goa', '4 Days / 3 Nights', 15000.00, 12000.00, 'Relax and unwind on the beautiful beaches of Goa. Enjoy water sports, nightlife, and delicious seafood. Visit historic churches and forts.', 'Day 1: Arrival in Goa, Beach visit\nDay 2: Water sports, Fort Aguada\nDay 3: Old Goa churches, Spice plantation\nDay 4: Departure', '• Hotel accommodation\n• Breakfast\n• Transportation\n• Water sports activities', '• Lunch and Dinner\n• Airfare\n• Personal expenses', 1, 'active'),

('Rajasthan Royal Tour', 'rajasthan-royal-tour', 'Rajasthan', '7 Days / 6 Nights', 35000.00, NULL, 'Explore the royal heritage of Rajasthan. Visit Jaipur, Udaipur, Jodhpur, and Jaisalmer. Experience camel safaris, palace visits, and traditional Rajasthani culture.', 'Day 1: Arrival in Jaipur\nDay 2: Jaipur city tour\nDay 3: Drive to Udaipur\nDay 4: Udaipur sightseeing\nDay 5: Drive to Jodhpur\nDay 6: Jodhpur and Jaisalmer\nDay 7: Departure', '• Hotel accommodation\n• All meals\n• Transportation\n• Guide services\n• Entry tickets', '• Airfare\n• Personal expenses\n• Tips', 1, 'active'),

('Kerala Backwaters Experience', 'kerala-backwaters-experience', 'Kerala', '6 Days / 5 Nights', 28000.00, 25000.00, 'Cruise through the serene backwaters of Kerala on a traditional houseboat. Visit tea plantations, enjoy Ayurvedic spa treatments, and experience the natural beauty of God\'s Own Country.', 'Day 1: Arrival in Cochin\nDay 2: Munnar hill station\nDay 3: Tea plantation visit\nDay 4: Houseboat cruise\nDay 5: Alleppey backwaters\nDay 6: Departure', '• Accommodation\n• All meals\n• Houseboat cruise\n• Transportation\n• Ayurvedic spa session', '• Airfare\n• Personal expenses\n• Additional activities', 0, 'active'),

('Himachal Hill Station Tour', 'himachal-hill-station-tour', 'Himachal Pradesh', '5 Days / 4 Nights', 20000.00, NULL, 'Escape to the cool hills of Himachal Pradesh. Visit Shimla, Manali, and enjoy adventure activities like paragliding and river rafting.', 'Day 1: Arrival in Shimla\nDay 2: Shimla sightseeing\nDay 3: Drive to Manali\nDay 4: Manali activities\nDay 5: Departure', '• Hotel accommodation\n• Breakfast\n• Transportation\n• Guide services', '• Lunch and Dinner\n• Airfare\n• Adventure activities\n• Personal expenses', 0, 'active'),

('Andaman Island Adventure', 'andaman-island-adventure', 'Andaman', '6 Days / 5 Nights', 32000.00, 29000.00, 'Discover the pristine beaches and coral reefs of Andaman Islands. Enjoy snorkeling, scuba diving, and water sports in this tropical paradise.', 'Day 1: Arrival in Port Blair\nDay 2: Cellular Jail, Ross Island\nDay 3: Havelock Island\nDay 4: Snorkeling and water sports\nDay 5: Radhanagar Beach\nDay 6: Departure', '• Hotel accommodation\n• All meals\n• Ferry transfers\n• Snorkeling equipment\n• Transportation', '• Airfare\n• Scuba diving\n• Personal expenses', 1, 'active');

-- Update site content with more details
UPDATE site_content SET content_value = '<h2>Welcome to Avipro Travels</h2><p>Avipro Travels is a leading travel agency dedicated to providing exceptional travel experiences. We offer carefully curated travel packages to stunning destinations around the world.</p><p>With years of experience in the travel industry, we understand that every journey is unique. Our team of travel experts works tirelessly to create memorable experiences that exceed expectations.</p><h3>Our Commitment</h3><p>We are committed to providing:</p><ul><li>Best-in-class travel packages</li><li>Competitive pricing</li><li>24/7 customer support</li><li>Safe and secure travel arrangements</li><li>Personalized service</li></ul>' WHERE content_key = 'about_us_content';

